server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: jmeter-test-app
  
  datasource:
    url: jdbc:mysql://localhost:3306/jmeter
    username: root
    password: viethoang123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        enable_lazy_load_no_trans: true
  
  security:
    user:
      name: admin
      password: admin123

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24 hours
